services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - TZ=UTC
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      # These variables are used for login and are standard Grafana env vars
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      # These variables are passed for datasource provisioning
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      # Mounts the provisioning configurations into Grafana's default provisioning path
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      # Mounts your dashboard JSON files to the path specified in dashboard.yml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      # Keeps Grafana data (like user settings, starred dashboards etc.) persistent
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  saultrade_app:
    build: .
    container_name: saultrade_app
    depends_on:
      - redis
      - influxdb
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python -u simulation.py"

volumes:
  influxdb_data:
  grafana_data:

networks:
  default:
    name: saultrade_network