services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myadmintoken
      - TZ=Asia/Kolkata
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - TZ=Asia/Kolkata
    volumes:
      - grafana_data:/var/lib/grafana

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Kolkata

  saultrade_app:
    build: .
    container_name: saultrade_app
    depends_on:
      - redis
      - influxdb
    environment:
      - CONFIG_FILE=/app/creds/config.yaml
      - RULES_FILE=/app/creds/tbs_rules.yaml
      - TZ=Asia/Kolkata
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: >
      sh -c "python -u simulation.py"

volumes:
  influxdb_data:
  grafana_data:

networks:
  default:
    name: saultrade_network