"user": "FA324706"
"pwd": "Shoonya@1819"
"vc": "FA324706_U"
"app_key": "1ace587d772ffa46ca73053d0a051c48"
"imei": "abc1234"
"secret": "7E5YER64Y5VE257GY7D265X6472CLICK"
redis:
  host: redis
  port: 6379

influxdb:
  url: "http://localhost:8086"
  token: "SX8w9NAK7TYD-PgKGPnYvomkTt8gQiX-2eJkDz1ZdJM3uM-YiqyUifaNHn8ANMo97klaH_PFsVeC3F8gqqHRCQ=="
  org: "myorg"
  bucket: "mybucket"