"user": "FA324706"
"pwd": "Shoonya@1819"
"vc": "FA324706_U"
"app_key": "1ace587d772ffa46ca73053d0a051c48"
"imei": "abc1234"
"secret": "7E5YER64Y5VE257GY7D265X6472CLICK"
redis:
  host: redis
  port: 6379

influxdb:
  url: "http://influxdb:8086"
  token: "WUkfdjYosrKE-kDqu_kNivNw0B3A5T7SdPAvIP00miGm0HbIPxe_3zVfw0TciJwqXs89PQtcS06pQj1TYWgaWQ=="
  org: "myorg"
  bucket: "mybuk"