"user": "FA324706"
"pwd": "Shoonya@1819"
"vc": "FA324706_U"
"app_key": "1ace587d772ffa46ca73053d0a051c48"
"imei": "abc1234"
"secret": "7E5YER64Y5VE257GY7D265X6472CLICK"
redis:
  host: localhost
  port: 6379

influxdb:
  url: "http://localhost:8086"
  token: "njS9K0BUzPGIY0uXQ8oYsKlhnbua7WDyy0Htvbpz8FZ7j7aRTmRF9DiAVe4dP5UNFy-d4TO7K8ZMnBYGokBnZQ=="
  org: "myorg"
  bucket: "mybuk"